std::exception_ptr

   From cppreference.com
   < cpp | error

   C++
   Compiler support
   Freestanding and hosted
   Language
   Standard library
   Standard library headers
   Named requirements
   Feature test macros (C++20)
   Language support library
   Concepts library (C++20)
   Metaprogramming library (C++11)
   Diagnostics library
   General utilities library
   Strings library
   Containers library
   Iterators library
   Ranges library (C++20)
   Algorithms library
   Numerics library
   Localizations library
   Input/output library
   Filesystem library (C++17)
   Regular expressions library (C++11)
   Concurrency support library (C++11)
   Technical specifications
   Symbols index
   External libraries

   Diagnostics library
   Exception handling
   exception
   uncaught_exceptionuncaught_exceptions
   (until C++20*)(C++17)
   exception_ptr
   (C++11)
   make_exception_ptr
   (C++11)
   current_exception
   (C++11)
   rethrow_exception
   (C++11)
   nested_exception
   (C++11)
   throw_with_nested
   (C++11)
   rethrow_if_nested
   (C++11)
   Exception handling failures
   terminate
   terminate_handler
   get_terminate
   (C++11)
   set_terminate
   bad_exception
   unexpected
   (until C++17*)
   unexpected_handler
   (until C++17*)
   get_unexpected
   (C++11)(until C++17*)
   set_unexpected
   (until C++17*)
   Error codes
   Error codes
   errno
   Exception categories
   logic_error
   invalid_argument
   domain_error
   length_error
   out_of_range
   runtime_error
   range_error
   overflow_error
   underflow_error
   tx_exception
   (TM TS)
   System error support
   error_category
   (C++11)
   generic_category
   (C++11)
   system_category
   (C++11)
   error_condition
   (C++11)
   errc
   (C++11)
   error_code
   (C++11)
   system_error
   (C++11)
   Assertions
   assert
   Stacktrace
   stacktrace_entry
   (C++23)
   basic_stacktrace
   (C++23)

   Defined in header <exception>
   typedef /*unspecified*/ exception_ptr;
                                         (since C++11)

   std::exception_ptr is a nullable pointer-like type that manages an
   exception object which has been thrown and captured with
   std::current_exception. An instance of std::exception_ptr may be passed
   to another function, possibly on another thread, where the exception
   may be rethrown and handled with a catch clause.

   A default-constructed std::exception_ptr is a null pointer; it does not
   point to an exception object.

   Two instances of std::exception_ptr compare equal only if they are both
   null or both point at the same exception object.

   std::exception_ptr is not implicitly convertible to any arithmetic,
   enumeration, or pointer type. It is contextually convertible to bool,
   and will evaluate to false if it is null, true otherwise.

   The exception object referenced by an std::exception_ptr remains valid
   as long as there remains at least one std::exception_ptr that is
   referencing it: std::exception_ptr is a shared-ownership smart pointer
   (note: this is in addition to the usual exception object lifetime
   rules).

   std::exception_ptr meets the requirements of NullablePointer.

Example

   Run this code
#include <exception>
#include <iostream>
#include <stdexcept>
#include <string>

void handle_eptr(std::exception_ptr eptr) // passing by value is ok
{
    try
    {
        if (eptr)
            std::rethrow_exception(eptr);
    }
    catch(const std::exception& e)
    {
        std::cout << "Caught exception: '" << e.what() << "'\n";
    }
}

int main()
{
    std::exception_ptr eptr;

    try
    {
        std::string().at(1); // this generates a std::out_of_range
    }
    catch(...)
    {
        eptr = std::current_exception(); // capture
    }

    handle_eptr(eptr);

} // destructor for std::out_of_range called here, when the eptr is destructed

   Possible output:
Caught exception: 'basic_string::at: __n (which is 1) >= this->size() (which is
0)'

See also

   make_exception_ptr
   (C++11)
   creates an std::exception_ptr from an exception object
   (function template)
   current_exception
   (C++11)
   captures the current exception in a std::exception_ptr
   (function)
   rethrow_exception
   (C++11)
   throws the exception from an std::exception_ptr
   (function)
   Retrieved from
   "https://en.cppreference.com/mwiki/index.php?title=cpp/error/exception_
   ptr&oldid=148679"

Navigation

     * Online version
     * Offline version retrieved 2024-06-10 08:17.

     * This page was last modified on 28 February 2023, at 10:12.
     * This page has been accessed 244,397 times.
